# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run tests"
  lane :test do
    destination =
      if ENV["SIMULATOR_UDID"] && !ENV["SIMULATOR_UDID"].empty?
        "platform=iOS Simulator,id=#{ENV['SIMULATOR_UDID']}"
      else
        "platform=iOS Simulator,name=iPhone 16"
      end

    run_tests(
      scheme: "CICDDemoApp",
      clean: true,
      destination: destination,
      output_directory: "fastlane/test_output",
      output_types: "junit"
    )
  end

  desc "CI lane"
  lane :ci do
    test

    UI.success("✅ CI Passed Successfully")
  end

end